name: flutter_vless
description: Flutter plugin to run VLESS/VMESS as a local proxy and VPN on Android, iOS, macOS, and Windows. V2Ray/Xray core. Shadowsocks, Trojan, Socks 5 support.

version: 1.0.5
homepage: https://github.com/XIIIFOX/flutter_vless/
tags:
     - VLESS
     - v2ray
     - xray
     - proxy
     - vpn
     - VMESS

topics:
  - vpn
  - vless
  - v2ray
  - xray
  - vmess

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_vless_platform_interface: ^1.0.0
  flutter_vless_android: ^1.0.2
  flutter_vless_macos: ^1.0.0
  flutter_vless_windows: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        default_package: flutter_vless_android
      ios:
        pluginClass: FlutterVlessPlugin
      macos:
        default_package: flutter_vless_macos
      windows:
        default_package: flutter_vless_windows

dependency_overrides:
  flutter_vless_platform_interface:
    path: packages/flutter_vless_platform_interface
  flutter_vless_android:
    path: packages/flutter_vless_android
  flutter_vless_macos:
    path: packages/flutter_vless_macos
  flutter_vless_windows:
    path: packages/flutter_vless_windows
