name: flutter_vless_macos
description: macOS implementation of the flutter_vless plugin.
version: 1.1.0
homepage: https://github.com/XIIIFOX/flutter_vless/

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_vless_platform_interface: ^1.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: flutter_vless_platform_interface
    platforms:
      macos:
        pluginClass: FlutterVlessPlugin

dependency_overrides:
  flutter_vless_platform_interface:
    path: ../flutter_vless_platform_interface
